#!/bin/sh

# create simlinks to dotfiles
ln -s ~/dotfiles/zsh/.zshrc ~/.zshrc
ln -s ~/dotfiles/gitconfig/.gitconfig ~/.gitconfig
ln -s ~/dotfiles/gitconfig/.gitconfig-personal ~/.gitconfig-personal
ln -s ~/dotfiles/tmux/.tmux.conf ~/.tmux.conf

# install homebrew
# TODO: add correct variant to install local for one user
# /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# install all packages from Brewfile
brew bundle --file ~/dotfiles/Brewfile

# configuering nvm
source $(brew --prefix nvm)/nvm.sh\n\n

# install oh-my-zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# after installing oh my zsh remove default zshrc and come back to link from dotfiles
rm ~/.zshrc && mv ~/.zshrc.pre-oh-my-zsh ~/.zshrc

# clone oh my zsh plugins
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
git clone https://github.com/zsh-users/zsh-completions ${ZSH_CUSTOM:=~/.oh-my-zsh/custom}/plugins/zsh-completions
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions


# create simlinks to directories in ~/.config
ln -sv ~/dotfiles/nvim ~/.config/
ln -sv ~/dotfiles/lf ~/.config/
ln -sv ~/dotfiles/kitty ~/.config/

