#!/bin/sh

# create simlinks to dotfiles
ln -s ~/dotfiles/zsh/.zshrc ~/.zshrc
ln -s ~/dotfiles/gitconfig/.gitconfig ~/.gitconfig
ln -s ~/dotfiles/gitconfig/.gitconfig-personal ~/.gitconfig-personal
ln -s ~/dotfiles/tmux/.tmux.conf ~/.tmux.conf

# install homebrew
# TODO: add correct variant to install local for one user
# /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# install all packages from Brewfile
brew bundle --file ~/.dotfiles/Brewfile

# install oh-my-zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# create simlinks to directories in ~/.config
ln -sv ~/dotfiles/nvim ~/.config/
ln -sv ~/dotfiles/lf ~/.config/

