#!/bin/sh

# Check if Homebrew is installed, install if it isn't
if ! command -v brew &>/dev/null; then
    echo "Installing Homebrew..."
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
else
    echo "Homebrew is already installed."
fi

# Install all packages from Brewfile
brew bundle --file ~/dotfiles/Brewfile

# Configuring nvm
source $(brew --prefix nvm)/nvm.sh

# Check if Oh My Zsh is installed, install if it isn't
if [ ! -d "$HOME/.oh-my-zsh" ]; then
    echo "Installing Oh My Zsh..."
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
else
    echo "Oh My Zsh is already installed."
fi

# After installing Oh My Zsh, remove the default .zshrc and link the correct one from dotfiles
rm ~/.zshrc
ln -s ~/dotfiles/zsh/.zshrc ~/.zshrc
ln -s ~/dotfiles/gitconfig/.gitconfig ~/.gitconfig
ln -s ~/dotfiles/gitconfig/.gitconfig-personal ~/.gitconfig-personal
ln -s ~/dotfiles/tmux/.tmux.conf ~/.tmux.conf

# Clone Oh My Zsh plugins
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
git clone https://github.com/zsh-users/zsh-completions ${ZSH_CUSTOM:=~/.oh-my-zsh/custom}/plugins/zsh-completions
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

# Create symlinks to directories in ~/.config
ln -sv ~/dotfiles/nvim ~/.config/
ln -sv ~/dotfiles/lf ~/.config/
ln -sv ~/dotfiles/kitty ~/.config/

